apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: janne-app-echo
spec:
  selector:
    app: echo
  ports:
    - port: 32222
      nodePort: 32222
      targetPort: 80
  type: NodePort
