apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: janne-app-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - image: jannemattila/echo:1.0.14
          name: echo
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
